GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2F1bCIsImlhdCI6MTczMjA4ODg4NCwiZXhwIjoxNzMyMDg4OTE0fQ.PlLIKtd06M8NY3VBr3lppQMP7ZmSuhdAQ-Fv0HHwDAk
###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2F1bCIsImlhdCI6MTczMjA4ODg0N30.Hxby5vEcF7wOuEiu2gwDOfcis86GiiOS2bEIesq1RTM"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2F1bCIsImlhdCI6MTczMjA4ODg0N30.Hxby5vEcF7wOuEiu2gwDOfcis86GiiOS2bEIesq1RTM"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Saul"
}

###
GET http://localhost:3000/

###
POST https://groupproject34.vercel.app/login
Content-Type: application/json

{
    "username": "Saul"
}

###
GET http://localhost:3000/forms/abcxyz

###
POST http://localhost:3000/forms/
Content-Type: application/json

{
  "name": "Internship Application Form",
  "description": "A form for internship applications",
  "fields": [
    { "label": "Name", "type": "text", "required": true },
    { "label": "Email", "type": "email", "required": true },
    { "label": "Resume", "type": "file", "required": false }
  ]
}

###
GET http://localhost:3000/forms/978ca102-4c54-48fb-9a0e-08b1de453db4